### ISSUE TITLE
Division des API calls pour les aéroports

### ISSUE THREAD

**Issue by sinclairfr** [maxroux/mai24_bde_airlines#2]

**Comment by sirinedhouib96** [comment]
[ayoub.txt](https://github.com/user-attachments/files/15764317/ayoub.txt)
[maxime.txt](https://github.com/user-attachments/files/15764318/maxime.txt)
[mehdi.txt](https://github.com/user-attachments/files/15764320/mehdi.txt)
[sirine.txt](https://github.com/user-attachments/files/15764321/sirine.txt)

**Comment by sirinedhouib96** [comment]
chaque fichier.txt contient la liste des codes aéroports à utiliser pour l'api GET /operations/flightstatus/departures/{airportCode}/{fromDateTime}
